# Generated by Django 5.0.7 on 2025-04-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_college_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='course',
        ),
    ]
